const JobPostModel = require('../Models/jobPostModel');

const createJobPost =async (req, res) => {

  try{
    const jData = req.body
    const {jobRole , experience , primarySkills, secondarySkills, jobDiscription, education, location, sector} =  jData;

    if (!jobRole || !experience || !primarySkills || !secondarySkills || !jobDiscription || !education || !location || !sector) return res.status(400).send({ message: 'Please fill all the fields' });
    if (!([
      "C",
      "Java",
      "Java Script",
      "Perl",
      "PHP",
      "Python",
      "Swift",
      "Go",
      "SQL",
      "R",
      "Ruby",
      "Google Suite",
      "Trello",
      "Slack",
      "Zapier",
      "Zoom",
      "JIRA",
      "Salesforce",
      "Budget planning",
      "Risk management",
      "Project planning",
      "PM tools",
      "Task management",
      "SCRUM methodology",
      "Agile methodology",
      "Product roadmaps",
      "User experience design",
      "Programming skills",
      "Product lifecycle management",
      "QA testingng",
      "Requirements gathering",
      "Coding",
      "Debugging",
      "Implementation",
      "Testing",
      "Design",
      "Configuration",
      "Applications",
      "Android",
      "Security",
      "Algorithms",
      "Modeling",
      "Documentation",
      "IOS",
      "Adobe creative ",
      "HTML",
      "Interactive media",
      "Wireframing",
      "UX research",
      "Prototyping",
      "Color theory",
      "Responsive design",
      "Photoshop",
      "Sketch",
      "User modeling",
      "Search Engine Optimization ",
      "Digital media",
      "Social media platforms",
      "Automated marketing software",
      "Content Management Systems ",
      "Copywriting",
      "Content creation",
      "Google Analytics",
      "Marketing analytics tools",
      "Accounting",
      "Word processing",
      "Spreadsheet building",
      "Coding",
      "Programming",
      "Operating equipment",
      "Engineering",
      "Experimenting",
      "Testing",
      "Constructing",
      "Restoring",
      "Product developing",
      "Quality controlling",
      "Blueprint drafting",
      "Repairing",
      "Translating",
      "Speaking",
      "Writing",
      "Conversing",
      "Reinterpreting",
      "Public speaking",
      "Following etiquette",
      "Explaining",
      "Respecting",
      "Signaling",
      "Proofreading",
      "Introducing",
      "Representing",
      "Rephrasing",
      "Code switching",
      "Graphic designing",
      "Illustrating",
      "Sketching",
      "Architecture",
      "User experience development",
      "User interface development",
      "Typography",
      "Layout development",
      "Web designing",
      "Interior designing",
      "Data visualizing",
      "Hierarchical arranging",
      "Aligning",
      "Photo and video editing",
      "Wireframing",
      "Researching",
      "Interpreting",
      "Information processing",
      "Organizing",
      "Processing",
      "Graphing",
      "Computing",
      "Calculating",
      "Modeling",
      "Extrapolating",
      "Predicting",
      "Forecasting",
      "Investigating",
      "Surveying",
      "Statistical analysis"
    ].includes(primarySkills))) return res.status(400).send({ status: false, message: "Please select value from the given option" })
    if (!([
      "Storytelling",
      "Written communication",
      "Editing",
      "Teaching",
      "Negotiating",
      "Open mindedness",
      "Inquiring",
      "Body language",
      "Customer service",
      "Presenting",
      "Summarizing",
      "Nonverbal communication",
      "Documenting",
      "Reporting",
      "Patience",
      "Positivity",
      "Conflict management",
      "Coaching",
      "Mediating",
      "Motivating",
      "Compassion",
      "Caring",
      "Networking",
      "Inspiring",
      "Flexibility",
      "Collaboration",
      "Sourcing feedback",
      "Reliability",
      "Empathy",
      "Observing",
      "Problem solving",
      "Inferring",
      "Simplifying",
      "Conceptual thinking",
      "Evaluating",
      "Streamlining",
      "Creative thinking",
      "Brainstorming",
      "Cost benefit analyzing",
      "Deductive reasoning",
      "Inductive reasoning",
      "Assessing",
      "Evidence collecting",
      "Troubleshooting",
      "Mentoring",
      "Envisioning",
      "Goal setting",
      "Employee development",
      "Performance reviewing",
      "Managing",
      "Planning",
      "Delegating",
      "Directing",
      "Supervising",
      "Training",
      "Earning trust",
      "Influencing",
      "Adapting",
      "Crisis managing"
    ].includes(secondarySkills))) return res.status(400).send({ status: false, message: "Please select value from the given option" })

    const jobPostData = await JobPostModel.create(jData);
    return res.status(201).send({status: true, message : "Job Post Data Created", data : jobPostData});
       
  }
  catch(err){
       return res.status(500).send({ status: false, Error: err.message })
       
  }

}

module.exports.createJobPost = createJobPost;