const mongoose = require("mongoose");

const jobPostSchema = new mongoose.Schema(
  {
    userDetailsID: {
      type: ObjectId,
      ref: "userPersonal"
    },
    jobRole: {
      type: String,
      required: true,
      enum: [
        "Marketing Manager",
        "Marketing Director",
        "Graphic Designer",
        "Marketing Research Analyst",
        "Marketing Communications Manager",
        "Marketing Consultant",-
        "Store Manager",
        "Account Executive",
        "Account Manager",
        "Area Sales Manager",
        "Direct Salesperson",
        "Director of Inside Sales",
        "Outside Sales Manager",
        "Sales Analyst",
        "Market Development Manager",
        "B2B Sales Specialist",
        "Sales Engineer",
        "Merchandising Associate",
        "CEO",
        "Proprietor",
        "Principal",
        "Owner",
        "President",
        "Founder",
        "Administrator",
        "Director",
        "Managing Partner",
        "Managing Member",
        "Board of Directors",
        "Shareholders",
        "Managers",
        "Supervisors",
        "Front Line Employees",
        "Quality Control",
        "Human Resources",
        "Accounting Staff",
        "Marketing Staff",
        "Purchasing Staff",
        "Shipping and Receiving Staff",
        "Office Manager",
        "Receptionist",
        "Virtual Assistant",
        "Customer Service",
        "Customer Support",
        "Concierge",
        "Help Desk",
        "Customer Service Manager",
        "Technical Support Specialist",
        "Account Representative",
        "Client Service Specialist",
        "Customer Care Associate",
        "Operations Manager",
        "Operations Assistant",
        "Operations Coordinator",
        "Operations Analyst",
        "Operations Director",
        "Vice President of Operations",
        "Operations Professional",
        "Scrum Master",
        "Continuous Improvement Lead",
        "Continuous Improvement Consultant",
        "Credit Authorizer",
        "Benefits Manager",
        "Credit Counselor",
        "Accountant",
        "Bookkeeper",
        "Accounting Analyst",
        "Accounting Director",
        "Accounts Payable Receivable Clerk",
        "Auditor",
        "Budget Analyst",
        "Controller",
        "Financial Analyst",
        "Finance Manager",
        "Economist",
        "Payroll Manager",
        "Payroll Clerk",
        "Financial Planner",
        "Financial Services Representative",
        "Finance Director",
        "Commercial Loan Office",
        "Engineer",
        "Mechanical Engineer",
        "Civil Engineer",
        "Electrical Engineer",
        "Assistant Engineer",
        "Chemical Engineer",
        "Chief Engineer",
        "Drafter",
        "Engineering Technician",
        "Geological Engineer",
        "Biological Engineer",
        "Maintenance Engineer",
        "Mining Engineer",
        "Nuclear Engineer",
        "Petroleum Engineer",
        "Plant Engineer",
        "Production Engineer",
        "Quality Engineer",
        "Safety Engineer",
        "Sales Engineer",
        "Chief People Officer",
        "VP of Miscellaneous Stuff",
        "Chief Robot Whisperer",
        "Director of First Impressions",
        "Culture Operations Manager",
        "Director of Ethical Hacking",
        "Software Engineer",
        "Director of Bean Counting",
        "Digital Overlord",
        "Director of Storytelling",
        "Researcher",
        "Research Assistant",
        "Data Analyst",
        "Business Analyst",
        "Financial Analyst",
        "Biostatistician",
        "Title Researcher",
        "Market Researcher",
        "Title Analyst",
        "Medical Researcher",
        "Mentor",
        "Online Tutor",
        "Teacher",
        "Teaching Assistant",
        "Substitute Teacher",
        "Preschool Teacher",
        "Test Scorer",
        "Online ESL Instructor",
        "Professor",
        "Assistant Professor"
      ]
    },
    experience: {
      type: Number,
      required: true,
    },
    primarySkills: {
      type: String,
      required: true,
      enum: [
        "C",
        "Java",
        "Java Script",
        "Perl",
        "PHP",
        "Python",
        "Swift",
        "Go",
        "SQL",
        "R",
        "Ruby",
        "Google Suite",
        "Trello",
        "Slack",
        "Zapier",
        "Zoom",
        "JIRA",
        "Salesforce",
        "Budget planning",
        "Risk management",
        "Project planning",
        "PM tools",
        "Task management",
        "SCRUM methodology",
        "Agile methodology",
        "Product roadmaps",
        "User experience design",
        "Programming skills",
        "Product lifecycle management",
        "QA testingng",
        "Requirements gathering",
        "Coding",
        "Debugging",
        "Implementation",
        "Testing",
        "Design",
        "Configuration",
        "Applications",
        "Android",
        "Security",
        "Algorithms",
        "Modeling",
        "Documentation",
        "IOS",
        "Adobe creative ",
        "HTML",
        "Interactive media",
        "Wireframing",
        "UX research",
        "Prototyping",
        "Color theory",
        "Responsive design",
        "Photoshop",
        "Sketch",
        "User modeling",
        "Search Engine Optimization ",
        "Digital media",
        "Social media platforms",
        "Automated marketing software",
        "Content Management Systems ",
        "Copywriting",
        "Content creation",
        "Google Analytics",
        "Marketing analytics tools",
        "Accounting",
        "Word processing",
        "Spreadsheet building",
        "Coding",
        "Programming",
        "Operating equipment",
        "Engineering",
        "Experimenting",
        "Testing",
        "Constructing",
        "Restoring",
        "Product developing",
        "Quality controlling",
        "Blueprint drafting",
        "Repairing",
        "Translating",
        "Speaking",
        "Writing",
        "Conversing",
        "Reinterpreting",
        "Public speaking",
        "Following etiquette",
        "Explaining",
        "Respecting",
        "Signaling",
        "Proofreading",
        "Introducing",
        "Representing",
        "Rephrasing",
        "Code switching",
        "Graphic designing",
        "Illustrating",
        "Sketching",
        "Architecture",
        "User experience development",
        "User interface development",
        "Typography",
        "Layout development",
        "Web designing",
        "Interior designing",
        "Data visualizing",
        "Hierarchical arranging",
        "Aligning",
        "Photo and video editing",
        "Wireframing",
        "Researching",
        "Interpreting",
        "Information processing",
        "Organizing",
        "Processing",
        "Graphing",
        "Computing",
        "Calculating",
        "Modeling",
        "Extrapolating",
        "Predicting",
        "Forecasting",
        "Investigating",
        "Surveying",
        "Statistical analysis"
      ]
    },
    secondarySkills: {
      type: String,
      required: true,
      enum: [
        "Storytelling",
        "Written communication",
        "Editing",
        "Teaching",
        "Negotiating",
        "Open mindedness",
        "Inquiring",
        "Body language",
        "Customer service",
        "Presenting",
        "Summarizing",
        "Nonverbal communication",
        "Documenting",
        "Reporting",
        "Patience",
        "Positivity",
        "Conflict management",
        "Coaching",
        "Mediating",
        "Motivating",
        "Compassion",
        "Caring",
        "Networking",
        "Inspiring",
        "Flexibility",
        "Collaboration",
        "Sourcing feedback",
        "Reliability",
        "Empathy",
        "Observing",
        "Problem solving",
        "Inferring",
        "Simplifying",
        "Conceptual thinking",
        "Evaluating",
        "Streamlining",
        "Creative thinking",
        "Brainstorming",
        "Cost benefit analyzing",
        "Deductive reasoning",
        "Inductive reasoning",
        "Assessing",
        "Evidence collecting",
        "Troubleshooting",
        "Mentoring",
        "Envisioning",
        "Goal setting",
        "Employee development",
        "Performance reviewing",
        "Managing",
        "Planning",
        "Delegating",
        "Directing",
        "Supervising",
        "Training",
        "Earning trust",
        "Influencing",
        "Adapting",
        "Crisis managing"
      ]
    },
    jobDiscription: {
      type: String,
      required: true
    },
    education: {
      type: String,
      required: true
    },
    location: {
      type: String,
      required: true,
      enum: [
        "Amaravati",
        "Anantapur",
        "Chandragiri",
        "Chittoor",
        "Dowlaiswaram",
        "Eluru",
        "Guntur",
        "Kadapa",
        "Kakinada",
        "Kurnool",
        "Machilipatnam",
        "Nagarjunako",
        "Rajahmundry",
        "Srikakulam",
        "Tirupati",
        "Vijayawada",
        "Visakhapatnam",
        "Vizianagaram",
        "Yemmiganur",
        "Itanagar",
        "Dhuburi",
        "Dibrugarh",
        "Dispur",
        "Guwahati",
        "Jorhat",
        "Nagaon",
        "Sivasagar",
        "Silchar",
        "Tezpur",
        "Tinsukia",
        "Ara",
        "Barauni",
        "Begusarai",
        "Bettiah",
        "Bhagalpur",
        "Bihar Sharif",
        "Bodh Gaya",
        "Buxar",
        "Chapra",
        "Darbhanga",
        "Dehri",
        "Dinapur Nizamat",
        "Gaya",
        "Hajipur",
        "Jamalpur",
        "Katihar",
        "Madhubani",
        "Motihari",
        "Munger",
        "Muzaffarpur",
        "Patna",
        "Purnia",
        "Pusa",
        "Saharsa",
        "Samastipur",
        "Sasaram",
        "Sitamarhi",
        "Siwan",
        "Chandigarh",
        "Ambikapur",
        "Bhilai",
        "Bilaspur",
        "Dhamtari",
        "Durg",
        "Jagdalpur",
        "Raipur",
        "Rajnandgaon",
        "Daman",
        "Diu",
        "Silvassa",
        "Delhi",
        "New Delhi",
        "Madgaon",
        "Panaji",
        "Ahmadabad",
        "Amreli",
        "Bharuch",
        "Bhavnagar",
        "Bhuj",
        "Dwarka",
        "Gandhinagar",
        "Godhra",
        "Jamnagar",
        "Junagadh",
        "Kandla",
        "Khambhat",
        "Kheda",
        "Mahesana",
        "Morbi",
        "Nadiad",
        "Navsari",
        "Okha",
        "Palanpur",
        "Patan",
        "Porbandar",
        "Rajkot",
        "Surat",
        "Surendranagar",
        "Valsad",
        "Veraval",
        "Ambala",
        "Bhiwani",
        "Chandigarh",
        "Faridabad",
        "Firozpur",
        "Jhirka",
        "Gurugram",
        "Hansi",
        "Hisar",
        "Jind",
        "Kaithal",
        "Karnal",
        "Kurukshetra",
        "Panipat",
        "Pehowa",
        "Rewari",
        "Rohtak",
        "Sirsa",
        "Sonipat",
        "Bilaspur",
        "Chamba",
        "Dalhousie",
        "Dharmshala",
        "Hamirpur",
        "Kangra",
        "Kullu",
        "Mandi",
        "Nahan",
        "Shimla",
        "Una",
        "Anantnag",
        "Baramula",
        "Doda",
        "Gulmarg",
        "Jammu",
        "Kathua",
        "Punch",
        "Rajouri",
        "Srinagar",
        "Udhampur",
        "Bokaro",
        "Chaibasa",
        "Deoghar",
        "Dhanbad",
        "Dumka",
        "Giridih",
        "Hazaribag",
        "Jamshedpur",
        "Jharia",
        "Rajmahal",
        "Ranchi",
        "Saraikela",
        "Badami",
        "Ballari",
        "Bengaluru",
        "Belagavi",
        "Bhadravati",
        "Bidar",
        "Chikkamagaluru",
        "Chitradurga",
        "Davangere",
        "Halebid",
        "Hassan",
        "Hubballi Dharwad",
        "Kalaburagi",
        "Kolar",
        "Madikeri",
        "Mandya",
        "Mangaluru",
        "Mysuru",
        "Raichur",
        "Shivamogga",
        "Shravanabelagola",
        "Shrirangapattana",
        "Tumakuru",
        "Vijayapura",
        "Alappuzha",
        "Vatakara",
        "Idukki",
        "Kannur",
        "Kochi",
        "Kollam",
        "Kottayam",
        "Kozhikode",
        "Mattancheri",
        "Palakkad",
        "Thalassery",
        "Thiruvananthapuram",
        "Thrissur",
        "Kargil",
        "Leh",
        "Balaghat",
        "Barwani",
        "Betul",
        "Bharhut",
        "Bhind",
        "Bhojpur",
        "Bhopal",
        "Burhanpur",
        "Chhatarpur",
        "Chhindwara",
        "Damoh",
        "Datia",
        "Dewas",
        "Dhar",
        "Mhow",
        "Guna",
        "Gwalior",
        "Hoshangabad",
        "Indore",
        "Itarsi",
        "Jabalpur",
        "Jhabua",
        "Khajuraho",
        "Khandwa",
        "Khargone",
        "Maheshwar",
        "Mandla",
        "Mandsaur",
        "Morena",
        "Murwara",
        "Narsimhapur",
        "Narsinghgarh",
        "Narwar",
        "Neemuch",
        "Nowgong",
        "Orchha",
        "Panna",
        "Raisen",
        "Rajgarh",
        "Ratlam",
        "Rewa",
        "Sagar",
        "Sarangpur",
        "Satna",
        "Sehore",
        "Seoni",
        "Shahdol",
        "Shajapur",
        "Sheopur",
        "Shivpuri",
        "Ujjain",
        "Vidisha",
        "Ahmadnagar",
        "Akola",
        "Amravati",
        "Aurangabad",
        "Bhandara",
        "Bhusawal",
        "Bid",
        "Buldhana",
        "Chandrapur",
        "Daulatabad",
        "Dhule",
        "Jalgaon",
        "Kalyan",
        "Karli",
        "Kolhapur",
        "Mahabaleshwar",
        "Malegaon",
        "Matheran",
        "Mumbai",
        "Nagpur",
        "Nanded",
        "Nashik",
        "Osmanabad",
        "Pandharpur",
        "Parbhani",
        "Pune",
        "Ratnagiri",
        "Sangli",
        "Satara",
        "Sevagram",
        "Solapur",
        "Thane",
        "Ulhasnagar",
        "Vasai Virar",
        "Wardha",
        "Yavatmal",
        "Imphal",
        "Cherrapunji",
        "Shillong",
        "Aizawl",
        "Lunglei",
        "Kohima",
        "Mon",
        "Phek",
        "Wokha",
        "Zunheboto",
        "Balangir",
        "Baleshwar",
        "Baripada",
        "Bhubaneshwar",
        "Brahmapur",
        "Cuttack",
        "Dhenkanal",
        "Kendujhar",
        "Konark",
        "Koraput",
        "Paradip",
        "Phulabani",
        "Puri",
        "Sambalpur",
        "Udayagiri",
        "Karaikal",
        "Mahe",
        "Puducherry",
        "Yanam",
        "Amritsar",
        "Batala",
        "Chandigarh",
        "Faridkot",
        "Firozpur",
        "Gurdaspur",
        "Hoshiarpur",
        "Jalandhar",
        "Kapurthala",
        "Ludhiana",
        "Nabha",
        "Patiala",
        "Rupnagar",
        "Sangrur",
        "Abu",
        "Ajmer",
        "Alwar",
        "Amer",
        "Barmer",
        "Beawar",
        "Bharatpur",
        "Bhilwara",
        "Bikaner",
        "Bundi",
        "Chittaurgarh",
        "Churu",
        "Dhaulpur",
        "Dungarpur",
        "Ganganagar",
        "Hanumangarh",
        "Jaipur",
        "Jaisalmer",
        "Jalor",
        "Jhalawar",
        "Jhunjhunu",
        "Jodhpur",
        "Kishangarh",
        "Kota",
        "Merta",
        "Nagaur",
        "Nathdwara",
        "Pali",
        "Phalodi",
        "Pushkar",
        "Sawai Madhopur",
        "Shahpura",
        "Sikar",
        "Sirohi",
        "Tonk",
        "Udaipur",
        "Gangtok",
        "Gyalshing",
        "Lachung",
        "Mangan",
        "Arcot",
        "Chengalpattu",
        "Chennai",
        "Chidambaram",
        "Coimbatore",
        "Cuddalore",
        "Dharmapuri",
        "Dindigul",
        "Erode",
        "Kanchipuram",
        "Kanniyakumari",
        "Kodaikanal",
        "Kumbakonam",
        "Madurai",
        "Mamallapuram",
        "Nagappattinam",
        "Nagercoil",
        "Palayamkottai",
        "Pudukkottai",
        "Rajapalayam",
        "Ramanathapuram",
        "Salem",
        "Thanjavur",
        "Tiruchchirappalli",
        "Tirunelveli",
        "Tiruppur",
        "Thoothukudi",
        "Udhagamandalam",
        "Vellore",
        "Hyderabad",
        "Karimnagar",
        "Khammam",
        "Mahbubnagar",
        "Nizamabad",
        "Sangareddi",
        "Warangal",
        "Agartala",
        "Agra",
        "Aligarh",
        "Amroha",
        "Ayodhya",
        "Azamgarh",
        "Bahraich",
        "Ballia",
        "Banda",
        "Bara Banki",
        "Bareilly",
        "Basti",
        "Bijnor",
        "Bithur",
        "Budaun",
        "Bulandshahr",
        "Deoria",
        "Etah",
        "Etawah",
        "Faizabad",
        "Farrukhabad cum Fatehgarh",
        "Fatehpur",
        "Fatehpur Sikri",
        "Ghaziabad",
        "Ghazipur",
        "Gonda",
        "Gorakhpur",
        "Hamirpur",
        "Hardoi",
        "Hathras",
        "Jalaun",
        "Jaunpur",
        "Jhansi",
        "Kannauj",
        "Kanpur",
        "Lakhimpur",
        "Lalitpur",
        "Lucknow",
        "Mainpuri",
        "Mathura",
        "Meerut",
        "Mirzapur Vindhyachal",
        "Moradabad",
        "Muzaffarnagar",
        "Partapgarh",
        "Pilibhit",
        "Prayagraj",
        "Rae Bareli",
        "Rampur",
        "Saharanpur",
        "Sambhal",
        "Shahjahanpur",
        "Sitapur",
        "Sultanpur",
        "Tehri",
        "Varanasi",
        "Almora",
        "Dehra Dun",
        "Haridwar",
        "Mussoorie",
        "Nainital",
        "Pithoragarh",
        "Alipore",
        "Alipur Duar",
        "Asansol",
        "Baharampur",
        "Bally",
        "Balurghat",
        "Bankura",
        "Baranagar",
        "Barasat",
        "Barrackpore",
        "Basirhat",
        "Bhatpara",
        "Bishnupur",
        "Budge Budge",
        "Burdwan",
        "Chandernagore",
        "Darjeeling",
        "Diamond Harbour",
        "Dum Dum",
        "Durgapur",
        "Halisahar",
        "Haora",
        "Hugli",
        "Ingraj Bazar",
        "Jalpaiguri",
        "Kalimpong",
        "Kamarhati",
        "Kanchrapara",
        "Kharagpur",
        "Cooch Behar",
        "Kolkata",
        "Krishnanagar",
        "Malda",
        "Midnapore",
        "Murshidabad",
        "Nabadwip",
        "Palashi",
        "Panihati",
        "Purulia",
        "Raiganj",
        "Santipur",
        "Shantiniketan",
        "Shrirampur",
        "Siliguri",
        "Siuri",
        "Tamluk",
        "Titagarh"
      ]
    },
    sector: {
      type: String,
      required: true,
      enum: [
        "Fishing industry",
        "Horticulture industry",
        "Tobacco industry",
        "Wood industry",
        "Mechanical Manufacturing",
        "Aerospace industry",
        "Automotive industry",
        "Chemical industry",
        "Pharmaceutical industry",
        "Construction industry",
        "Defense industry",
        "Arms industry",
        "Electric power industry",
        "Electronics industry",
        "Computer industry",
        "Semiconductor industry",
        "Energy industry",
        "Food industry",
        "Industrial robot industry",
        "Low technology industry",
        "Meat",
        "Meat packing",
        "Mining",
        "Petroleum industry",
        "Oil shale",
        "Pulp and paper industry",
        "Steel industry",
        "Shipbuilding industry",
        "Telecommunications industry",
        "Textile industry",
        "Water industry",
        "Creative",
        "Advertising",
        "Fashion",
        "Floral",
        "Cultural industry",
        "Culture industry",
        "Education industry",
        "Entertainment industry",
        "Film industry",
        "Gambling industry",
        "Music industry",
        "Sex industry",
        "Video game industry",
        "Financial services industry",
        "Insurance industry",
        "Healthcare industry",
        "Hospitality industry",
        "Information industry",
        "Leisure industry",
        "Mass media",
        "Broadcasting",
        "Internet",
        "News media",
        "Publishing",
        "Entertainment",
        "Professional services",
        "Real estate industry",
        "Retail industry",
        "Software industry",
        "Sport industry",
        "Transport industry"
      ],
    }
  },
  { timestamps: true }
);

module.exports = mongoose.model("jobPost", jobPostSchema);